apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In ## we could have (NotIn, Exists) too.
            values:
            - large
            - medium            
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent



Three types of nodes affinity: 
- requiredDuringSchedulingIgnoredDuringExecution
## during Scheduling means when scheduling the new pods for the first time.
## during Execution means for the existing running pods. for ignored means nothing will happen to the running pods if we change the key value of the node
- preferredDuringSchedulingIgnoredDuringExecution
- requiredDuringSchedulingRequiredDuringExecution

