apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  USER_NAME: YWRtaW4=
  PASSWORD: MWYyZDFlMmU2N2Rm

==== username and password must be encoded.

example : echo -n 'mysql' | base64

==== To decode use 

example: echo -n 'YWRtaW4=' | base64 --decode


k get secrets
k describe secrets

k get secrets app-secret -o yaml




apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
   name: nginx_app
spec:     
  containers:
  - name: nginx
    image: nginx
    ports: 
     - containerPort: 8080
    envFrom:
     -secretRef:
       name: app-secret


IN VOLUME

  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: special-config
  restartPolicy: Never


