apiVersion: v1
kind: Pod
metadata: 
 name: simple-webapp
spec:
 containers:
  - name: simple-webapp
    image: simple-webapp
 tolerations:
  - key: "app"
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule"


____To delete a taint add (-)
kubectl taint nodes <node-name> <taint-key>-

kubectl taint nodes node1 key1=value1:NoSchedule
kubectl taint nodes node1 key1=value1:NoSchedule-
