apiVersion: v1
kind: Pod
metadata: 
 name: simple-webapp
spec:
 containers:
  - name: simple-webapp
    image: simple-webapp
 tolerations:
  - key: "app"
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule"