apiVersion: v1
kind: Pod
metadata:
  name: goproxy
  labels:
    app: goproxy
spec:
  containers:
  - name: goproxy
    image: registry.k8s.io/goproxy:0.1
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket: # 1-httpGet 2-tcpSocket 3-exec 
        port: 8080
      initialDelaySeconds: 5 # wait before executing 
      periodSeconds: 10
    livenessProbe: # liveness probes dont wait for readiness Probe we need to use initialDelaySeconds
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20