apiVersion: v1
kind: Pod
metadata: 
 name: simple-webapp
 labels:
  name: simple-webapp
spec:
 containers:
  - name: simple-webapp
    image: simple-webapp
 nodeSelector:
  size: Large ## the label setted in the node


 ## command to add label to a node 
 kubectl label nodes <node-name> <label-key>=<label-value>
 kubectl label nodes node-1 size=Large 