apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-2
spec:
  # at a pod level
  securityContext:
    runAsUser: 1000 # the user ID
  containers:
  - name: sec-ctx-demo-2
    image: gcr.io/google-samples/node-hello:1.0
    # at a container level
    securityContext:
      runAsUser: 2000
      capabilities:
        add: ["MAC_ADMIN"]

________If you configure it at a pod level,

the settings will carry-over to all the containers within the pod.

________If you configure it at both the pod and the container,

the settings on the container will override the settings on the pod.

