apiVersion: v1
kind: CronJob
metadata:
  name: reporting-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate: 
   spec: 
    completions: 3
    parallelism: 3      => will create pods in the same time
    template:
      spec:
      containers: 
        - name: test
          image: ubuntu
          command: ['expr', '3', '+', '2']
      restartPolicy: Never


kubectl create -f cron.yaml

kubectl get cronjob